### ISSUE TITLE
build failed  'config.h.in' not found

### ISSUE THREAD

**Issue by ComputingFroggy** [peckto/gdar#1]
The build process is quite complicated. I had to install the build tools and I still have an error when building ... a shame a DEB is not proposed.

$ ./autogen.sh  
configure.ac:23: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:23: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:8: error: required file 'config.h.in' not found
configure.ac:23: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library

**Comment by peckto** [comment]
I'm sorry for the difficult build process. It seams like you are missing some gettext library. The INSTALL file lists necessary packages for different distributions. If this list is not complete for you, I can look up additional packages for you when you give me more details about your system setup. You can now also find binary packages for Debian 8 on the Open Suse Buildservice at https://software.opensuse.org/download.html?project=home%3Apeckto&package=gdar. Older Debian versions do not provide the necessary version of libdar. I cant provide packages for Ubuntu at the moment, because the Buildservice does not provide the necessary dependencies. I'm working on a solution. I hope I could help you to get gdar running.

**Comment by KarlZeilhofer** [comment]
I also couldn't build the application on linux mint 17.3. 
I tried to install dar from source to get the new libdar installed - without any luck. 
There you find what I did, except of the manual installation of dar:
http://www.zeilhofer.co.at/wiki/doku.php?id=gdar&#prerequisits

I also got the error for the missing config.h.in, but after autogen.sh the file was there...

dar --version: 
    2.5.3
/sbin/ldconfig -v | grep libdar
    libdar64.so.5000 -> libdar64.so.5000.7.3
    libdar.so.5000 -> libdar.so.5000.7.3

@ make, it stops with this error:
g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-3.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/atk-1.0 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/harfbuzz   -DLIBDAR_MODE=64 -std=c++11 -I/usr/local/include   -DGDAR_LOCALEDIR=\"/usr/local/share/locale\"   -g -O2 -MT gdar.o -MD -MP -MF .deps/gdar.Tpo -c -o gdar.o gdar.cpp
In file included from /usr/local/include/dar/limitint.hpp:60:0,
                 from /usr/local/include/dar/infinint.hpp:41,
                 from /usr/local/include/dar/compressor.hpp:31,
                 from /usr/local/include/dar/libdar.hpp:77,
                 from mylibdar.hpp:26,
                 from gdar.cpp:22:
/usr/local/include/dar/on_pool.hpp:37:51: fatal error: /usr/local/include/dar/cygwin_adapt.hpp: No such file or directory
 #include "/usr/local/include/dar/cygwin_adapt.hpp"

I'm not sure, if this has to do with the manual installation of dar. 
To get the new version of dar working, I had to uninstall libdar with "apt-get remove"...

Kind regards, 
Karl

**Comment by peckto** [comment]
Hi Karl,

The cygwin_adapt.hpp is missing in dar release since version 2.5.1 and will be fixed in the next release.
See: http://sourceforge.net/p/dar/mailman/message/34750943/.
For now I recommend you to use dar version 2.4.20.
I hope this will fix your problem and you can now compile gdar successfully.

Best regards,
Tobias
